[[mgr.prepend_keymap]]
on   = "q"
run  = "quit --no-cwd-file"
desc = "Quit without outputting cwd-file"

[[mgr.prepend_keymap]]
on   = "Q"
run  = "quit"
desc = "Quit the process"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
